name: liftgate-client
main: io.liftgate.client.platform.spigot.LiftgateSpigotPlatformPlugin

version: ${pluginVersion}
description: ${pluginDescription}
website: https://liftgate.io

api-version: 1.19
folia-supported: true

# mccoroutine & kotlin
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.4.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.4.0
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4
  - org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.4
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.10
