name: liftgate-client
main: io.liftgate.client.platform.spigot.LiftgateSpigotPlatformPlugin
version: unknown

description: Game server management, orchestration, and scaling platform.
website: https://liftgate.io

api-version: 1.19

# mccoroutine & kotlin
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.4.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.4.0
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.2
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.10
